### ISSUE TITLE
cannot found bisenet.pth

### ISSUE THREAD

**Issue by ForrestPi** [lstcutong/video-face-3d#1]
very useful tools, thanks !  but I  cannot found bisenet.pth could you provide it?

**Comment by lstcutong** [comment]
bisenet.pth updated, hope you enjoy it!

**Comment by lstcutong** [comment]
> very useful tools, thanks ! but I cannot found bisenet.pth could you provide it?

bisenet.pth updated, hope you enjoy it!

**Comment by ForrestPi** [comment]
@lstcutong     thanks !
