### ISSUE TITLE
视频数据集处理问题

### ISSUE THREAD

**Issue by deepdarkfans** [lstcutong/video-face-3d#2]
你好，请问一下如何将视频处理成单帧的图片，我在这个项目的example中没有看到，

**Comment by lstcutong** [comment]
> 你好，请问一下如何将视频处理成单帧的图片，我在这个项目的example中没有看到，

你说的将视频处理成单帧的图片是指处理成以人脸为中心的对齐后的图像序列还是指啥？如果是我说的这个的话，首先你需要用我代码中的关键点检测器检测每一帧的68人脸关键点，然后将图片路径和对应关键点送入我们提供的vf3d.alignment_and_crop(image_path, landmarks)函数中（具体见util.geometry.alignment_and_crop），即可得到，在example_sfs_single_image.py的17,18行有使用的参考样例，希望对你有用！

**Comment by deepdarkfans** [comment]
是的，就是将视频处理成人脸为中心的对齐后的图像序列，我先用的example_video.py先试了一下300vw中的第一个视频，发现其中的关键点检测并不是很准确，如图，总是检测到其他的人脸，而且一个视频的处理速度很慢，感觉因为是用CPU跑的原因，
![image](https://user-images.githubusercontent.com/33440182/110466454-a8c11380-808a-11eb-9776-63b701ed031a.png)
之后我看了看你在另一个项目KDFReVS-3D中的训练集，发现都检测到了主要的人脸

**Comment by lstcutong** [comment]
> 是的，就是将视频处理成人脸为中心的对齐后的图像序列，我先用的example_video.py先试了一下300vw中的第一个视频，发现其中的关键点检测并不是很准确，如图，总是检测到其他的人脸，而且一个视频的处理速度很慢，感觉因为是用CPU跑的原因，
> ![image](https://user-images.githubusercontent.com/33440182/110466454-a8c11380-808a-11eb-9776-63b701ed031a.png)
> 之后我看了看你在另一个项目KDFReVS-3D中的训练集，发现都检测到了主要的人脸

这个example_video.py里面还有一些bug，目前暂时没时间完善，参考价值不是很大，后续会完善这个repo的；检测到其他人脸是因为在代码里我只使用了检测到的第一个人的人脸关键点（因为为了方便调试，其余检测到的人脸我暂时扔了，这就可能会把主要人脸扔掉，你可以试试加上再看看结果）。另外KDFReVS-3D的数据集手工后处理很多，所以基本都是主要的人脸，后续KDFReVS-3D使用的数据集（手工处理好的）应该也会放出来，还请耐心等待吧。至于速度慢你还是先放GPU上跑吧，我这边GPU跑的很快的。

**Comment by deepdarkfans** [comment]
好的，谢谢了

**Comment by deepdarkfans** [comment]
对了，还有个问题请教，你的那个KDFReVS-3D的训练集，就是以视频序列为训练集的是吧，CelebA等一些2D的图像数据集训练的效果不好是吗，还是因为网络结构本身就是专门来训练视频序列的？

**Comment by lstcutong** [comment]
> 对了，还有个问题请教，你的那个KDFReVS-3D的训练集，就是以视频序列为训练集的是吧，CelebA等一些2D的图像数据集训练的效果不好是吗，还是因为网络结构本身就是专门来训练视频序列的？

这个请持续关注一下我们后续的一些研究报告吧，我目前只能说，KDFReVS-3D还有很多要完善的。

**Comment by deepdarkfans** [comment]
> > 对了，还有个问题请教，你的那个KDFReVS-3D的训练集，就是以视频序列为训练集的是吧，CelebA等一些2D的图像数据集训练的效果不好是吗，还是因为网络结构本身就是专门来训练视频序列的？
> 
> 这个请持续关注一下我们后续的一些研究报告吧，我目前只能说，KDFReVS-3D还有很多要完善的。

行的，我还想关注一下你们的论文，找不到只不过

**Comment by lstcutong** [comment]
> > > 对了，还有个问题请教，你的那个KDFReVS-3D的训练集，就是以视频序列为训练集的是吧，CelebA等一些2D的图像数据集训练的效果不好是吗，还是因为网络结构本身就是专门来训练视频序列的？
> > 
> > 
> > 这个请持续关注一下我们后续的一些研究报告吧，我目前只能说，KDFReVS-3D还有很多要完善的。
> 
> 行的，我还想关注一下你们的论文，找不到只不过

再等一阵吧，目前还未公开
